### ISSUE TITLE
Process tab isn't aligned correctly

### ISSUE THREAD

**Issue by wolf-yuan-6115** [innovara/sysmotd#1]
![image](https://github.com/innovara/sysmotd/assets/58245644/2c15c55c-4653-4c8f-8148-42d4bbbb59b5)
It happened on both machine running Fedora 38

**Comment by innovara** [comment]
Yes, I was aware that my initial approach based on tabs was too basic and bound to produce misalignments like that.
I published a new version that uses a table and it seems to produce consistent alignments.
Thank you for reporting and I hope you find the little tool helpful.
