### ISSUE TITLE
Allow install without downloading package manaully

### ISSUE THREAD

**Issue by wolf-yuan-6115** [innovara/sysmotd#2]
You can use 
```sh
sudo dnf install https://github.com/innovara/sysmotd/releases/download/0.0.4/sysmotd-0.0.4-1.fc39.noarch.rpm
```
to install package directly without downloading package by yourself

**Comment by innovara** [comment]
I've updated the documentation but I am not too sure this would be very useful because you always need the link since the RPMs have the versions embedded in their names.

**Comment by wolf-yuan-6115** [comment]
> I've updated the documentation but I am not too sure this would be very useful because you always need the link since the RPMs have the versions embedded in their names.

I don't like to download the file, and remove it after install. Maybe someone will find it useful.
